#! /bin/bash
ps -aux|grep -v 'root'
read -p "请输入要查询的PID: " P
n=`ps -aux| awk '$2~/^'$P'$/{print $11}'|wc -l`
if [ $n -eq 0 ];then
 echo -e "\033 "该PID不存在！！"[31m\033[0m" 
 exit
fi
echo -e "\033[31m   --------------------------------\033[0m"
echo -e "\033[32m   "进程PID: $P" \033[0m" 
echo -e "\033[32m   "进程命令：`ps -aux| awk '$2~/^'$P'$/{print $11}'`" \033[0m" 
echo -e "\033[32m   "进程所属用户: `ps -aux| awk '$2~/^'$P'$/{print $1}'`" \033[0m" 
echo -e "\033[32m   "CPU占用率：`ps -aux| awk '$2~/^'$P'$/{print $3}'`%" \033[0m" 
echo -e "\033[32m   "内存占用率：`ps -aux| awk '$2~/^'$P'$/{print $4}'`%" \033[0m" 
echo -e "\033[32m   "进程开始运行的时刻：`ps -aux| awk '$2~/^'$P'$/{print $9}'`" \033[0m" 
echo -e "\033[32m   "进程运行的时间：`ps -aux| awk '$2~/^'$P'$/{print $10}'`" \033[0m" 
echo -e "\033[32m   "进程状态：`ps -aux| awk '$2~/^'$P'$/{print $8}'`" \033[0m"
echo -e "\033[32m   "进程虚拟内存：`ps -aux| awk '$2~/^'$P'$/{print $5}'`" \033[0m" 
echo -e "\033[32m   "进程共享内存：`ps -aux| awk '$2~/^'$P'$/{print $6}'`" \033[0m" 
echo -e "\033[31m -------------------------------- \033[0m" 
